kind: pipeline
name: default

steps:
- name: check ansible syntax
  image: plugins/ansible:1
  environment:
    another_var: foo
  settings:
    playbook: main.yml
    galaxy: molecule/default/requirements.yml
    inventory: inventory
    syntax_check: true
  when:
    event:
    - pull_request

- name: apply ansible playbook
  image: plugins/ansible:1
  environment:
    additional_var:
      from_secret: additional_var
  settings:
    playbook: main.yml
    galaxy: molecule/default/requirements.yml
    inventory: inventory
    private_key:
      from_secret: ansible_private_key
    vault_password:
      from_secret: ansible_vault_password
  when:
    event:
    - push
    - tag