kind: pipeline
name: default

steps:
- name: Apply Ansible Playbook
  image: plugins/ansible:1
  settings:
    playbook: main.yml
    galaxy: molecule/default/requirements.yml
    inventory: inventory
    syntax_check: true
    private_key:
      from_secret: ansible_private_key
    user:
      from_secret: ansible_user