---
downloads: ~/.ansible-downloads/
configure_dotfiles: true
dotfiles_repo: https://github.com/dueyfinster/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/.dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore
  - .inputrc
  - .ssh/config
  - .tmuxinator
  - .vim
  - .vimrc
  - bin
homebrew_installed_packages:
  - coreutils
  - git
  - hledger
  - ledger
  - ssh-copy-id
  - vim
homebrew_taps:
  - homebrew/bundle
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - homebrew/services
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - eclipse-jee
  - emacs
  - firefox
  - hazel
  - plex
  - sonos
  - steam
  - visual-studio-code
